export function memoryPanelCopy() {
  return {
    title: "Knowledge Notes",
    subtitle: "Saved and proposed notes. Source, approval, and Oak review decide what can be reused.",
    stats: {
      saved: "Saved",
      trusted: "Ready",
      proposed: "Proposed",
    },
    contractTitle: "Reuse Contract",
    contractLoading: "Reading reuse contract.",
    contractNoWrite: "No retrieval automation",
    contractRouteLabel: "Route",
    contractReviewLabel: "Review",
    contractGateLabel: "Gate",
    contractNextLabel: "Next",
    contractRouteValue: (normalRoute: string, archiveRoute: string) => `${normalRoute} / ${archiveRoute}`,
    contractReviewValue: (pending: number, validated: number) => `${pending} pending, ${validated} Oak validated`,
    searchPlaceholder: "Search.",
    allRunsLabel: "All Runs",
    inputPlaceholder: "New knowledge note. Enter to stage.",
    stageTitleEmpty: "Enter a knowledge note before staging it.",
    stageTitleReady: "Stage a local knowledge note for review. It is not reusable yet.",
    stageAria: "Stage local knowledge note",
    routingTitle: "Note Routing",
    kindLabel: "Note kind",
    runLinkLabel: "Run link",
    noRunLink: "No run link",
    tagsPlaceholder: "tags, comma-separated",
    proposedTitle: "Proposed",
    oakLabel: "Oak",
    loadingText: "Reading knowledge notes.",
    emptyText: "No notes yet. Save facts, notes, references, or feedback when they are useful later.",
    deleteTitle: "Open the hard-gate confirmation before deleting this local note.",
    deleteDialogTitle: "Delete Knowledge Note",
    deleteDialogDescription: "This removes a saved local knowledge note. Cancel keeps the note visible.",
    cancelDeleteTitle: "Keep the knowledge note visible.",
    confirmDeleteTitle: "Permanently delete this local knowledge note after confirmation.",
    confirmDeleteAria: "Confirm delete knowledge note",
    deletingText: "Deleting",
    deleteButton: "Delete Note",
  };
}
