export function outputsPanelCopy() {
  return {
    title: "Saved Outputs",
    subtitle: "Notes, drafts, reports, prompts, and saved files. Details keep destination and retention visible.",
    stats: {
      saved: "Saved",
      writing: "Writing",
      trail: "Trail",
    },
    kindFilterAria: "Saved output kind filters",
    runFilterAria: "Saved output run filters",
    kindLabel: "Output type",
    runLinkLabel: "Run link",
    noRunLink: "No run link",
    titlePlaceholder: (label: string) => `${label} title`,
    saveTitleEmpty: "Add a title and body before saving an output.",
    saveTitleObsidian: "Write a local Obsidian note and keep it in Saved Outputs.",
    saveTitleVault: "Write a local vault file and keep it in Saved Outputs.",
    saveAriaObsidian: "Save local Obsidian note",
    saveAriaVault: "Save local vault file",
    savingText: "Saving",
    saveText: "Save",
    routingTitle: "Save Routing",
    obsidianSubdirPlaceholder: "Obsidian subfolder",
    sourcePlaceholder: "Source URL or file path",
    contextPlaceholder: "Optional source/context URI",
    ownerPrefix: "Owner",
    historyNote: "These controls save durable history, drafts, and reports. Current-state updates need a separate approved writer.",
    loadingText: "Reading saved outputs.",
    emptyText: "No saved outputs match this filter. Save a note, draft, report, prompt, or file.",
    detailsTitle: "Output Details",
    savedVaultText: (path?: string) => `Saved vault output${path ? `: ${path}` : "."}`,
    fallbackTitle: (id: number) => `Output ${id}`,
    locationLabel: "Destination",
    keepLabel: "Retention",
    ownerLabel: "Owner",
  };
}
